apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: efsprovisioners.efs.storage.openshift.io
spec:
  group: efs.storage.openshift.io
  names:
    kind: EFSProvisioner
    listKind: EFSProvisionerList
    plural: efsprovisioners
    singular: efsprovisioner
  scope: Namespaced
  version: v1alpha1
