apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-provisioner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: efs-provisioner-operator
  template:
    metadata:
      labels:
        name: efs-provisioner-operator
    spec:
      serviceAccountName: efs-provisioner-operator
      containers:
        - name: efs-provisioner-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - efs-provisioner-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "efs-provisioner-operator"
